Add unit tests
Magda1921/CookBook pull request #2
Opened 2023-08-08 17:20 UTC by Magda1921

Add unit tests

2023-08-17 15:59 UTC, wswieciekodu commented
Please remove target - we dont commit it to repo, this is generated by compliler

2023-08-21 22:17 UTC, wswieciekodu requested changes

2023-08-21 22:17 UTC, wswieciekodu commented on src/main/java/cookbook/CookBook.java
> +        List<Recipe> recipes = fileOperations.readRecipes(fileName);
same with nameOfRecipe - declare it as close to use as possible - it increase readability of code

2023-08-21 22:17 UTC, wswieciekodu commented on src/main/java/cookbook/CookBook.java
>          System.out.println(recipes);
not needed

2023-08-21 22:17 UTC, wswieciekodu commented on src/main/java/cookbook/FileOperations.java
> +        Path pathCookbook = Paths.get("cookbook.txt");
make sense to store filename in one place in app, and then pass to places where needed. This will guarantee that all operations will use the same file and when filename change you will change only in one place

2023-08-21 22:17 UTC, wswieciekodu commented on src/main/java/cookbook/FileOperations.java
> +            e.printStackTrace();
make sense to add some meaningfull message for user rather than stacktrace

2023-08-21 22:17 UTC, wswieciekodu commented on src/main/java/cookbook/FileOperations.java
> +            return null;
better return List.of() - empty list, because null returning is bad practice because is can cause nullpointerexception

2023-08-21 22:17 UTC, wswieciekodu commented on src/test/java/cookbook/CookbookTest.java
> +        int expected = 2;
this test check nothing, please add assert

2023-08-21 22:17 UTC, wswieciekodu commented on src/test/java/cookbook/CookbookTest.java
> +        int expected = 2;
get currentId should rather not be public, and when not public we should test it by public method

2023-08-21 22:17 UTC, wswieciekodu commented on src/test/java/cookbook/FileOperationsTest.java
> +        List <Recipe> expected = new ArrayList<>();
formatter

2023-08-21 22:17 UTC, wswieciekodu commented on src/test/java/cookbook/FileOperationsTest.java
> +        Ingredient ingredient1 = new Ingredient();
declare as close as possible to use

2023-08-21 22:17 UTC, wswieciekodu commented on src/test/java/cookbook/FileOperationsTest.java
> +        Assertions.assertEquals(mapped, expected);
please do testing opertion just before assert.

You can follow rule:

//given 
<preparing test data>
//when
<run tested method>
//then
<veryfing using assert>

2023-08-21 22:17 UTC, wswieciekodu commented on src/test/java/cookbook/RecipeMapperTest.java
> +        String expected = "1;pesto;Place the basil leaves, garlic and olive oil into the bowl of a food processor and pulse several times.;1-basil-1.0-piece,2-garlic-4.0-cloves";
formatter, and test data dont need to be real, better create short test data, to make code more readable

2023-09-06 06:41 UTC, Magda1921 commented on src/main/java/cookbook/CookBook.java
>          int number = -1;
variable has been removed

2023-10-05 06:54 UTC, wswieciekodu requested changes

2023-10-05 06:54 UTC, wswieciekodu commented on src/main/java/cookbook/CookBook.java
> +import cookbook.Models.Ingredient;
packages name should be started with small letters - please rename to -> model

2023-10-05 06:54 UTC, wswieciekodu commented on src/main/java/cookbook/CookBook.java
>          System.out.println(recipes);
is this needed?

2023-10-05 06:54 UTC, wswieciekodu commented on src/main/java/cookbook/FileOperations.java
> +    public List<Recipe> readRecipes(String filename1) {
dont use names with 1,2,3 -> rename it to filename

2023-10-05 17:59 UTC, wswieciekodu approved these changes

2023-10-05 18:23 UTC, merged